
# Site
title: MINFIVE
subtitle: MINFIVE BLOG
subtitle_desc: 日常学习与兴趣交流
keywords: minfive, minfive blog, 前端博客, 前端, 程序员, 前端开发, 全栈开发, node.js, javascript
description: 日常学习与兴趣交流的个人博客
introduction: 不思量，自难忘！
logo: http://oo12ugek5.bkt.clouddn.com/images/base-logo.png
qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
default_cover: http://oo12ugek5.bkt.clouddn.com/images/default_cover.png
header_cover: http://oo12ugek5.bkt.clouddn.com/blog/images/banner-bg.jpg
error_page_bg: http://oo12ugek5.bkt.clouddn.com/blog/images/dogs.jpg
author:
  name: minfive
  link: https://github.com/Mrminfive
about:
  info: 本站是基于 Hexo 搭建的静态资源博客，主要用于分享日常学习、生活及工作的一些心得总结，欢迎点击右下角订阅 rss。

  address: Guangzhou, Guangdong Province, China
  email: chenxiaowu1994@outlook.com

# Menu
menu:
  home: /
  archive: /archives
  works: /demo
  music: /music
  about: /about

highlight_theme: normal

loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif
theme: jekyll-theme-architect